routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::view('/', 'welcome');

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use HasFactory;
}

app/Models/Geoobject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Geoobject extends Model
{
    use HasFactory;

    protected $fillable = ['city_id', 'name', 'lat', 'long'];
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'description', 'price', 'image'];


    public function getImagePathAttribute(): string
    {
        if (preg_match("/\bhttp\w*/i",$this->image)){
            return $this->image;
        }
        return asset('images/products/' . $this->image);
    }
}

app/Models/Restaurant.php
<?php

namespace App\Models;

use App\Observers\RestaurantObserver;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Restaurant extends Model
{
    use HasFactory;

    protected $fillable = [
        'owner_id',
        'name',
        'city_id',
        'address_street',
        'address_postcode',
        'lat',
        'long'
    ];

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'owner_id');
    }

    public static function booted()
    {
        parent::booted();
        self::observe(RestaurantObserver::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function restaurants()
    {
        return $this->hasMany(Restaurant::class, 'owner_id');
    }
}

app/Http/Controllers/Api/Owner/RestaurantController.php
<?php

namespace App\Http\Controllers\Api\Owner;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreRestaurantRequest;
use App\Models\City;
use App\Models\Restaurant;
use Illuminate\Support\Facades\Auth;

class RestaurantController extends Controller
{
    public function store(StoreRestaurantRequest $request)
    {
         return auth()->user()->restaurants()->create($request->validated());
    }
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Models\Product;
use App\Services\ProductService;
use Symfony\Component\HttpFoundation\Response as ResponseAlias;

/**
 * @OA\Info(
 *      version="1.0.0",
 *      title="OrynTap API",
 *     description="OrynTap API Documentation",
 *     @OA\Contact(
 *     email="dsa@dsa.dsa"
 *    ),
 *     @OA\License(
 *     name="Apache 2.0",
 *     url="http://www.apache.org/licenses/LICENSE-2.0.html"
 *      )
 *  ),
 * @OA\Server(
 *     url=L5_SWAGGER_CONST_HOST,
 *     description="OrynTap API Server"
 * ),
 */
class ProductController extends Controller
{
    private $productService;
    public function __construct(ProductService $productService)
    {
        $this->productService = $productService;
    }

    /**
     * @OA\Get(
     *     path="/api/products",
     *     summary="Get all products",
     *     tags={"Products"},
     *     @OA\Response(
     *         response=200,
     *         description="List of products",
     *         @OA\JsonContent(
     *             type="array",
     *             @OA\Items(ref="#/components/schemas/ProductResource")
     *         )
     *     ),
     *     security={}
     * )
     */
    public function index()
    {
        $result = $this->productService->getAllProducts();

        return response()->json([
            'success'=> true,
            'data' => $result
        ], ResponseAlias::HTTP_OK);
    }
    /**
     * @OA\Post(
     *     path="/api/products",
     *     summary="Create a new product",
     *     tags={"Products"},
     *     @OA\RequestBody(
     *         required=true,
     *         @OA\JsonContent(ref="#/components/schemas/ProductRequest")
     *     ),
     *     @OA\Response(
     *         response=201,
     *         description="Product created successfully",
     *         @OA\JsonContent(ref="#/components/schemas/ProductResource")
     *     ),
     * )
     */
    public function store(ProductRequest $request)
    {
        $result = $this->productService->createProduct($request->validated());

        return response()->json([
            'success'=> true,
            'data' => $result,
            'message' => 'Product created successfully'
        ], ResponseAlias::HTTP_CREATED);
    }

    /**
     *
     * @OA\Get(
     *     path="/api/products/{id}",
     *     summary="Get a specific product",
     *     tags={"Products"},
     *     @OA\Parameter(
     *         name="id",
     *         in="path",
     *         required=true,
     *         description="ID of the product",
     *         @OA\Schema(type="integer")
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="Product details",
     *         @OA\JsonContent(ref="#/components/schemas/ProductResource")
     *     ),
     *     security={}
     * )
     */
    public function show(Product $product)
    {
        $result  = $this->productService->getProduct($product);
        return response()->json([
            'success'=> true,
            'data' => $result
        ], ResponseAlias::HTTP_OK);
    }

    /**
     * @OA\Put(
     *     path="/api/products/{id}",
     *     summary="Update a specific product",
     *     tags={"Products"},
     *     @OA\Parameter(
     *         name="id",
     *         in="path",
     *         required=true,
     *         description="ID of the product",
     *         @OA\Schema(type="integer")
     *     ),
     *     @OA\RequestBody(
     *         required=true,
     *         @OA\JsonContent(ref="#/components/schemas/ProductRequest")
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="Product updated successfully",
     *         @OA\JsonContent(ref="#/components/schemas/ProductResource")
     *     ),
     * )
     */

    public function update(ProductRequest $request, Product $product)
    {
        $result = $this->productService->updateProduct($product, $request->validated());

        return response()->json([
            'success'=> true,
            'data' => $result
        ], ResponseAlias::HTTP_OK);
    }

    /**
     * @OA\Delete(
     *     path="/api/products/{id}",
     *     summary="Delete a specific product",
     *     tags={"Products"},
     *     @OA\Parameter(
     *         name="id",
     *         in="path",
     *         required=true,
     *         description="ID of the product",
     *         @OA\Schema(type="integer")
     *     ),
     *     @OA\Response(
     *         response=204,
     *         description="Product deleted successfully"
     *     ),
     * )
     */

    public function destroy(Product $product): \Illuminate\Http\JsonResponse
    {
        $result = $this->productService->deleteProduct($product);

        return response()->json([
            'success'=> true,
            'message' => $result
        ], ResponseAlias::HTTP_NO_CONTENT);
    }

    public function export(): \Symfony\Component\HttpFoundation\BinaryFileResponse
    {
       return $this->productService->exportProducts();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;


class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp,container-queries"></script>
</head>
<body>
<header>
    @yield('content')
</header>
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')
@section('title', 'Product Create')
@section('content')
    <section class="flex flex-row justify-center">
        <div class="shadow-lg mt-48 p-6 rounded-md content-center">
            <form action="{{route('products.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('POST')
                <div class="">
                    <h1 class="text-xl font-medium text-center m-5">Create Product</h1>
                    <label for="name" class="block font-medium text-sm text-gray-900 leading-7">Name</label>
                    <input type="text" name="name" id="name" class="rounded-md w-80 border-0 ring-1 ring-inset ring-gray-300 text-sm">

                </div>
                <div class="">
                    <label for="description" class="block font-medium text-sm text-gray-900 leading-7">Description</label>
                    <input type="text" name="description" id="description" class="rounded-md w-80 border-0 ring-1 ring-inset ring-gray-300 text-sm">
                </div>
                <div class="">
                    <label for="price" class="block text-sm font-medium text-gray-900 leading-6">Price</label>
                    <input type="number" class="rounded-md w-80 border-0 ring-1 ring-inset ring-gray-300 text-sm" name="price" id="price">
                </div>
                <div>
                    <label for="image" class="block text-sm font-medium text-gray-900 leading-6">Image</label>
                    <input type="file" class="block w-full text-sm text-slate-500
      file:mr-4 file:py-2 file:px-4
      file:rounded-full file:border-0
      file:text-sm file:font-semibold
      file:bg-violet-50 file:text-violet-700
      hover:file:bg-violet-100
    "/>
                </div>
                <button class="bg-violet-700 hover:bg-violet-900 mt-2  text-white px-2 py-2 px-4 font-semibold border-0 text-sm rounded-full">Create</button>
            </form>
        </div>
    </section>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('title', 'Products')
@section('content')


    <div class="bg-white py-24 sm:py-32">
        <div class="mx-auto max-w-7xl px-6 lg:px-8">
            <div class="mx-auto max-w-2xl lg:mx-0">


                <a href="{{route('products.create')}}">Create Product</a>
                <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Products</h2>
                <p class="mt-2 text-lg leading-8 text-gray-600">Learn how to grow your business with our expert advice.</p>
            </div>
            <div class="mx-auto mt-10 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 border-t border-gray-200 pt-10 sm:mt-16 sm:pt-16 lg:mx-0 lg:max-w-none lg:grid-cols-3">
                @foreach($products as $product)
                <article class="flex max-w-xl flex-col items-start justify-between shadow-lg">
                    <div class="group relative">
                            <a href="#">
                                <img class="p-8 justify-center rounded-t-lg w-44 h-56" src="{{ $product->image_path }}" alt="product image" />
                            </a>
                            <div class="px-5 pb-5">
                                <a href="#">
                                    <h5 class="text-xl font-semibold tracking-tight text-gray-900 dark:text-white">{{ $product->name }}</h5>
                                    <div class="p-3 gap-x-4 text-xs">
                                        <a href="#" class="relative z-10 rounded-full bg-gray-50 px-3 py-1.5 font-medium text-gray-600 hover:bg-gray-100">Marketing</a>
                                    </div>
                                </a>
                                <div class="flex items-center mt-2.5 mb-5">
                                    <div class="flex items-center space-x-1 rtl:space-x-reverse">
                                        <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                            <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                        </svg>
                                        <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                            <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                        </svg>
                                    </div>
                                    <span class="bg-blue-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ms-3">5.0</span>
                                </div>
                                <div class="flex items-center justify-between">
                                    <span class="text-md font-bold text-gray-900 dark:text-white">{{ $product->price }} KZT</span>
                                    <a href="#" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add to cart</a>
                                </div>
                            </div>
                    </div>
                </article>
                @endforeach
            </div>
        </div>
    </div>
@endsection